services:
  postgres:
    labels:
      - "traefik.enable=false"
    networks:
      - web

  redis:
    labels:
      - "traefik.enable=false"
    networks:
      - web

  backend:
    labels:
      - "traefik.enable=false"
    ports:
      - "8001:${BACKEND_PORT}"

  # telegram_bot:
  #   labels:
  #     - "traefik.enable=false"
  #   ports:
  #     - "8443:${TELEGRAM_BOT_PORT}"
